In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000/tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000/tmdb_5000_credits.csv')

# 1 Data

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

## 1.1 Data Preprocessing

In [5]:
# run only one time
movies = movies.merge(credits, on='title')

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [8]:
feature = ['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']

movies = movies[feature]

In [9]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.duplicated().sum()

np.int64(0)

In [12]:
movies.iloc[0]

movie_id                                                19995
title                                                  Avatar
overview    In the 22nd century, a paraplegic Marine is di...
genres      [{"id": 28, "name": "Action"}, {"id": 12, "nam...
keywords    [{"id": 1463, "name": "culture clash"}, {"id":...
cast        [{"cast_id": 242, "character": "Jake Sully", "...
crew        [{"credit_id": "52fe48009251416c750aca23", "de...
Name: 0, dtype: object

### Genres

In [13]:
movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [14]:
# '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# ['Action', 'Adventure', 'Fantasy', 'SciFi']

In [15]:
import ast

In [16]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])

    return L

In [17]:
convert(movies['genres'][0])

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [18]:
movies['genres'] = movies['genres'].apply(convert)

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

### Keywords

In [20]:
movies.iloc[0].keywords

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [21]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

### Cast

In [22]:
movies.iloc[0].cast

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [23]:
def convert_cast(obj):
    L = []
    cnt = 0
    for i in ast.literal_eval(obj):
        if(cnt >= 4):
            break
        L.append(i['name'])
        cnt+=1
    return L

In [24]:
movies['cast'] = movies['cast'].apply(convert_cast)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

### Crew

In [25]:
movies.iloc[0].crew

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [26]:
def convert_crew(obj):
    L = []

    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break

    return L

In [27]:
movies['crew'] = movies['crew'].apply(convert_crew)

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

### Overview

In [29]:
movies['overview'] = movies['overview'].apply(lambda x : x.split())

### Removing space

In [30]:
movies['genres']= movies['genres'].apply(lambda x : [i.replace(" ", "") for i in x])
movies['keywords']= movies['keywords'].apply(lambda x : [i.replace(" ", "") for i in x])
movies['cast']= movies['cast'].apply(lambda x : [i.replace(" ", "") for i in x])
movies['crew']= movies['crew'].apply(lambda x : [i.replace(" ", "") for i in x])

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

### Joining

In [32]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [33]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

### New DF & some changes

In [34]:
df = movies[['movie_id', 'title', 'tags']]

In [35]:
df['tags'] = df['tags'].apply(lambda x : " ".join(x))

C:\Users\admin\AppData\Local\Temp\ipykernel_15844\1642297555.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(lambda x : " ".join(x))

In [36]:
df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [37]:
df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang JamesCameron'

In [38]:
df['tags'] = df['tags'].apply(lambda x : x.lower())

C:\Users\admin\AppData\Local\Temp\ipykernel_15844\3023486031.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(lambda x : x.lower())

In [39]:
df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

### Removing Similler Word

In [40]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [41]:
def stem(text):
    L = []

    for i in text.split():
        L.append(ps.stem(i))
    
    return " ".join(L)

In [42]:
df['tags'] = df['tags'].apply(stem)

C:\Users\admin\AppData\Local\Temp\ipykernel_15844\866399325.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(stem)

In [43]:
df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

## 1.2 Vectorization

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

In [45]:
vectors = cv.fit_transform(df['tags']).toarray()

In [46]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

### Vector Analysis

In [47]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

### Consine Similarity

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [49]:
similarity

array([[1.        , 0.08458258, 0.08585457, ..., 0.04559608, 0.        ,
        0.        ],
       [0.08458258, 1.        , 0.05970814, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.08585457, 0.05970814, 1.        , ..., 0.02414023, 0.        ,
        0.        ],
       ...,
       [0.04559608, 0.02378257, 0.02414023, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]], shape=(4806, 4806))

# 2. Main Function

By giving movie name it gives us similer movies

## 2.1 Fetching Index

In [50]:
df[df['title'] == 'Avatar'].index[0]

np.int64(0)

## 2.2 Similarity by index

In [51]:
similarity[0]

array([1.        , 0.08458258, 0.08585457, ..., 0.04559608, 0.        ,
       0.        ], shape=(4806,))

## 2.3 Sorting the distance

similarity list has similarity score between two movies
<br>
similarity[0] has score of similarity between all the movies with respect to the movie on the 0th index 
<br>
so if we sort the list we can't say like movie at the 0th index has higher similarity with movie at 8th index
<br>

In [52]:
sorted(similarity[0], reverse=True)

[np.float64(0.9999999999999998),
 np.float64(0.29061909685954823),
 np.float64(0.25903973506580724),
 np.float64(0.25732511773283273),
 np.float64(0.2500965064695278),
 np.float64(0.2484013136974297),
 np.float64(0.24507154069793594),
 np.float64(0.24239308278185984),
 np.float64(0.23490461932490855),
 np.float64(0.23490461932490855),
 np.float64(0.23249527748763854),
 np.float64(0.22830583024432843),
 np.float64(0.22482004035239062),
 np.float64(0.22147019900891643),
 np.float64(0.2102998911698345),
 np.float64(0.20878692266483084),
 np.float64(0.20795009796401454),
 np.float64(0.2071841649822589),
 np.float64(0.20712325533373332),
 np.float64(0.20668850837512243),
 np.float64(0.20608503698969144),
 np.float64(0.2056773510573183),
 np.float64(0.20549873413169661),
 np.float64(0.20343336780168372),
 np.float64(0.20323743847971518),
 np.float64(0.20134681656420733),
 np.float64(0.2005648842255601),
 np.float64(0.20032733246124987),
 np.float64(0.20032733246124987),
 np.float64(0.1979131233319198),
 np.float64(0.19184045508446734),
 np.float64(0.19101436199010396),
 np.float64(0.18983159915049982),
 np.float64(0.1898315991504998),
 np.float64(0.1898315991504998),
 np.float64(0.1898315991504998),
 np.float64(0.18944220058835154),
 np.float64(0.18857857160117855),
 np.float64(0.18641092980036),
 np.float64(0.18427434427242975),
 np.float64(0.1841637022064523),
 np.float64(0.18380365552345193),
 np.float64(0.18316875326179907),
 np.float64(0.18316875326179907),
 np.float64(0.17937400083354382),
 np.float64(0.17757120130114434),
 np.float64(0.17757120130114434),
 np.float64(0.17757120130114434),
 np.float64(0.1771615786072478),
 np.float64(0.1771615786072478),
 np.float64(0.1754942736973651),
 np.float64(0.1754942736973651),
 np.float64(0.1742014225237369),
 np.float64(0.17348855898381338),
 np.float64(0.17170914210964275),
 np.float64(0.17155007848855516),
 np.float64(0.17139779254776524),
 np.float64(0.1696751579473019),
 np.float64(0.16916516233038026),
 np.float64(0.16916516233038026),
 np.float64(0.1678603981989089),
 np.float64(0.1675306779862365),
 np.float64(0.16702953813186466),
 np.float64(0.16610264925668733),
 np.float64(0.1643989873053573),
 np.float64(0.1643989873053573),
 np.float64(0.16240619866164335),
 np.float64(0.16216216216216217),
 np.float64(0.16216216216216217),
 np.float64(0.16120647005479025),
 np.float64(0.16120647005479025),
 np.float64(0.15949044456578),
 np.float64(0.15819299929208316),
 np.float64(0.15608456220771372),
 np.float64(0.1559625734730109),
 np.float64(0.1559625734730109),
 np.float64(0.15404884978892902),
 np.float64(0.15393156857680898),
 np.float64(0.15042366316917008),
 np.float64(0.15042366316917008),
 np.float64(0.15042366316917008),
 np.float64(0.15042366316917005),
 np.float64(0.15007505629691606),
 np.float64(0.15007505629691606),
 np.float64(0.14982047586544328),
 np.float64(0.1487044791289829),
 np.float64(0.1487044791289829),
 np.float64(0.14763464883937316),
 np.float64(0.14704292441876157),
 np.float64(0.14704292441876157),
 np.float64(0.14704292441876157),
 np.float64(0.14704292441876154),
 np.float64(0.14615084586538157),
 np.float64(0.14615084586538157),
 np.float64(0.1454358496691159),
 np.float64(0.1453095484297741),
 np.float64(0.1453095484297741),
 np.float64(0.1453095484297741),
 np.float64(0.1453095484297741),
 np.float64(0.1438803413133505),
 np.float64(0.14349920066683505),
 np.float64(0.14349920066683505),
 np.float64(0.14349920066683505),
 np.float64(0.14309095175803563),
 np.float64(0.14309095175803563),
 np.float64(0.14309095175803563),
 np.float64(0.1430909517580356),
 np.float64(0.14237369936287486),
 np.float64(0.14165281524036175),
 np.float64(0.14165281524036175),
 np.float64(0.14097096860865022),
 np.float64(0.14091341769030624),
 np.float64(0.14019992744655632),
 np.float64(0.14019992744655632),
 np.float64(0.14019992744655632),
 np.float64(0.14019992744655632),
 np.float64(0.1389425035941821),
 np.float64(0.1389425035941821),
 np.float64(0.1389425035941821),
 np.float64(0.1389425035941821),
 np.float64(0.1389425035941821),
 np.float64(0.13812277665483924),
 np.float64(0.1371182340382122),
 np.float64(0.1371182340382122),
 np.float64(0.13699915608779772),
 np.float64(0.13678822577626598),
 np.float64(0.13657399193174952),
 np.float64(0.1354916256531435),
 np.float64(0.13513513513513514),
 np.float64(0.1342312110428049),
 np.float64(0.1342312110428049),
 np.float64(0.1342312110428049),
 np.float64(0.1342312110428049),
 np.float64(0.13423121104280486),
 np.float64(0.13334518676566626),
 np.float64(0.13334518676566626),
 np.float64(0.13334518676566626),
 np.float64(0.13300532955644181),
 np.float64(0.13300532955644181),
 np.float64(0.1316245316231641),
 np.float64(0.13151918984428584),
 np.float64(0.13151918984428584),
 np.float64(0.13151918984428584),
 np.float64(0.13151918984428584),
 np.float64(0.13065106689280268),
 np.float64(0.12996881122750908),
 np.float64(0.12996881122750908),
 np.float64(0.12996881122750908),
 np.float64(0.12996881122750908),
 np.float64(0.12996881122750908),
 np.float64(0.12996881122750908),
 np.float64(0.1289651760438322),
 np.float64(0.1289651760438322),
 np.float64(0.1289651760438322),
 np.float64(0.1289651760438322),
 np.float64(0.1283740414907742),
 np.float64(0.1283740414907742),
 np.float64(0.1283740414907742),
 np.float64(0.12629480039223434),
 np.float64(0.12535305264097507),
 np.float64(0.12535305264097507),
 np.float64(0.12535305264097507),
 np.float64(0.1252721535988985),
 np.float64(0.12527215359889848),
 np.float64(0.12427395320024),
 np.float64(0.12427395320024),
 np.float64(0.12427395320024),
 np.float64(0.12427395320024),
 np.float64(0.12427395320024),
 np.float64(0.12427395320024),
 np.float64(0.12427395320024),
 np.float64(0.12392039927415242),
 np.float64(0.12329924047901797),
 np.float64(0.12329924047901797),
 np.float64(0.12329924047901797),
 np.float64(0.12329924047901797),
 np.float64(0.12253577034896797),
 np.float64(0.1221125021745327),
 np.float64(0.1221125021745327),
 np.float64(0.1221125021745327),
 np.float64(0.12119654139092992),
 np.float64(0.12119654139092992),
 np.float64(0.1211965413909299),
 np.float64(0.12050719759100866),
 np.float64(0.12050719759100866),
 np.float64(0.12006004503753284),
 np.float64(0.12006004503753284),
 np.float64(0.12006004503753284),
 np.float64(0.12006004503753284),
 np.float64(0.12006004503753284),
 np.float64(0.11990028442779209),
 np.float64(0.11961783342433499),
 np.float64(0.11961783342433499),
 np.float64(0.11961783342433499),
 np.float64(0.11961783342433499),
 np.float64(0.1186447494690624),
 np.float64(0.1186447494690624),
 np.float64(0.11810771907149853),
 np.float64(0.11810771907149853),
 np.float64(0.11810771907149852),
 np.float64(0.11806886145601307),
 np.float64(0.1178966237837789),
 np.float64(0.11742784807525519),
 np.float64(0.11742784807525519),
 np.float64(0.11742784807525519),
 np.float64(0.11742784807525519),
 np.float64(0.11706342165578529),
 np.float64(0.1166080974034697),
 np.float64(0.11624763874381927),
 np.float64(0.11624763874381927),
 np.float64(0.11624763874381927),
 np.float64(0.11624763874381927),
 np.float64(0.11624763874381927),
 np.float64(0.11510231387903269),
 np.float64(0.11507929111375009),
 np.float64(0.11466596451673744),
 np.float64(0.1144727614064285),
 np.float64(0.1144727614064285),
 np.float64(0.11399018814688831),
 np.float64(0.11399018814688831),
 np.float64(0.1139901881468883),
 np.float64(0.11394547734377711),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11290968804428622),
 np.float64(0.11290968804428622),
 np.float64(0.11277677488692017),
 np.float64(0.11277677488692017),
 np.float64(0.11277677488692017),
 np.float64(0.11277677488692017),
 np.float64(0.11241002017619531),
 np.float64(0.11185934253567072),
 np.float64(0.11168711865749101),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.1109779869250491),
 np.float64(0.11097798692504908),
 np.float64(0.11083777463036817),
 np.float64(0.11083777463036817),
 np.float64(0.11028219331407116),
 np.float64(0.11028219331407116),
 np.float64(0.1098436937909367),
 np.float64(0.1098436937909367),
 np.float64(0.1098436937909367),
 np.float64(0.1098436937909367),
 np.float64(0.10972379887386347),
 np.float64(0.10959932487023819),
 np.float64(0.10959932487023819),
 np.float64(0.10959932487023819),
 np.float64(0.10959932487023819),
 np.float64(0.10959932487023819),
 np.float64(0.10959932487023819),
 np.float64(0.10959932487023819),
 np.float64(0.10887588907733556),
 np.float64(0.10887588907733554),
 np.float64(0.10827079910776224),
 np.float64(0.10810810810810811),
 np.float64(0.10810810810810811),
 np.float64(0.10810810810810811),
 np.float64(0.10810810810810811),
 np.float64(0.10810810810810811),
 np.float64(0.10810810810810811),
 np.float64(0.10793322294408637),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.10701462561817378),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.1061190899945022),
 np.float64(0.1061190899945022),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10524566699352861),
 np.float64(0.10524566699352861),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10439346133241542),
 np.float64(0.10439346133241542),
 np.float64(0.10439346133241542),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10356162766686666),
 np.float64(0.10283867552865915),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10274936706584831),
 np.float64(0.10269923319261937),
 np.float64(0.10269923319261937),
 np.float64(0.10269923319261937),
 np.float64(0.10269923319261937),
 np.float64(0.10269923319261937),
 np.float64(0.10269923319261937),
 np.float64(0.1019559237857732),
 np.float64(0.10146925788636821),
 np.float64(0.10146925788636821),
 np.float64(0.1011805823145441),
 np.float64(0.1011805823145441),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10042266465917388),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.09968152785361249),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09802861627917438),
 np.float64(0.09802861627917438),
 np.float64(0.09802861627917438),
 np.float64(0.09802861627917438),
 np.float64(0.09802861627917438),
 np.float64(0.09802861627917438),
 np.float64(0.09802861627917438),
 np.float64(0.09695723311274393),
 np.float64(0.09687303228651607),
 np.float64(0.09687303228651607),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09592022754223367),
 np.float64(0.09555497043061453),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.09428928580058928),
 np.float64(0.09394227846020416),
 np.float64(0.09394227846020416),
 np.float64(0.09394227846020416),
 np.float64(0.09394227846020416),
 np.float64(0.09367501681349609),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.0930725988812425),
 np.float64(0.0930725988812425),
 np.float64(0.0930725988812425),
 np.float64(0.09299811099505542),
 np.float64(0.09299811099505542),
 np.float64(0.09299811099505542),
 np.float64(0.09299811099505542),
 np.float64(0.09208185110322616),
 np.float64(0.09208185110322616),
 np.float64(0.09208185110322616),
 np.float64(0.09208185110322616),
 np.float64(0.09208185110322616),
 np.float64(0.09208185110322616),
 np.float64(0.09208185110322616),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09097816785925636),
 np.float64(0.09032775043542898),
 np.float64(0.09032775043542898),
 np.float64(0.09032775043542898),
 np.float64(0.0902256659231352),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.08968700041677191),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08867021970429453),
 np.float64(0.08867021970429453),
 np.float64(0.08867021970429453),
 np.float64(0.08867021970429453),
 np.float64(0.0886379935648677),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08710071126186844),
 np.float64(0.08710071126186844),
 np.float64(0.08710071126186844),
 np.float64(0.08710071126186844),
 np.float64(0.0863465783552691),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08569889627388262),
 np.float64(0.08561170049453902),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08419653359482289),
 np.float64(0.08419653359482289),
 np.float64(0.08419653359482289),
 np.float64(0.08351476906593233),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08284930213349333),
 np.float64(0.08284930213349333),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08156473902861858),
 np.float64(0.08138962667412651),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08094446585163528),
 np.float64(0.08094446585163528),
 np.float64(0.08094446585163528),
 np.float64(0.0803381317273391),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.07983920607777244),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.0792290665533957),

to solve above issue we will use enumarate

## 2.4 Enumeration

In [53]:
# will give enumerate object
enumerate(similarity[0])

In [54]:
# by converting the enumerate object into list we will have, what we need (index, simillarity_score)

list(enumerate(similarity[0]))

[(0, np.float64(0.9999999999999998)),
 (1, np.float64(0.08458258116519013)),
 (2, np.float64(0.08585457105482137)),
 (3, np.float64(0.07398532461669939)),
 (4, np.float64(0.1898315991504998)),
 (5, np.float64(0.1098436937909367)),
 (6, np.float64(0.04078236951430929)),
 (7, np.float64(0.14704292441876157)),
 (8, np.float64(0.06003002251876642)),
 (9, np.float64(0.09802861627917438)),
 (10, np.float64(0.10269923319261937)),
 (11, np.float64(0.09491579957524991)),
 (12, np.float64(0.09158437663089952)),
 (13, np.float64(0.04559607525875532)),
 (14, np.float64(0.12996881122750908)),
 (15, np.float64(0.06974858324629157)),
 (16, np.float64(0.08000711205939975)),
 (17, np.float64(0.14165281524036175)),
 (18, np.float64(0.09687303228651607)),
 (19, np.float64(0.08489527199560176)),
 (20, np.float64(0.05858330335516624)),
 (21, np.float64(0.10810810810810811)),
 (22, np.float64(0.0685591170191061)),
 (23, np.float64(0.08718572905786445)),
 (24, np.float64(0.05405405405405406)),
 (25, np.float64(0.03465834966066909)),
 (26, np.float64(0.1559625734730109)),
 (27, np.float64(0.18944220058835154)),
 (28, np.float64(0.11115400287534567)),
 (29, np.float64(0.06532553344640132)),
 (30, np.float64(0.06711560552140243)),
 (31, np.float64(0.16120647005479025)),
 (32, np.float64(0.08561170049453902)),
 (33, np.float64(0.09672388203287416)),
 (34, np.float64(0.0)),
 (35, np.float64(0.09863939238321438)),
 (36, np.float64(0.17155007848855516)),
 (37, np.float64(0.07897471897389846)),
 (38, np.float64(0.08219949365267865)),
 (39, np.float64(0.08219949365267865)),
 (40, np.float64(0.07702442489446452)),
 (41, np.float64(0.16610264925668733)),
 (42, np.float64(0.0)),
 (43, np.float64(0.09208185110322616)),
 (44, np.float64(0.03427955850955305)),
 (45, np.float64(0.08351476906593233)),
 (46, np.float64(0.1389425035941821)),
 (47, np.float64(0.1979131233319198)),
 (48, np.float64(0.08419653359482289)),
 (49, np.float64(0.058123819371909635)),
 (50, np.float64(0.1144727614064285)),
 (51, np.float64(0.07974522228289)),
 (52, np.float64(0.14704292441876157)),
 (53, np.float64(0.04317328917763455)),
 (54, np.float64(0.03106848830006)),
 (55, np.float64(0.07050168600188522)),
 (56, np.float64(0.14019992744655632)),
 (57, np.float64(0.024507154069793594)),
 (58, np.float64(0.06774581282657174)),
 (59, np.float64(0.07306621658015879)),
 (60, np.float64(0.0186145197762485)),
 (61, np.float64(0.23490461932490855)),
 (62, np.float64(0.07974522228289)),
 (63, np.float64(0.08948747402853657)),
 (64, np.float64(0.029526929767874632)),
 (65, np.float64(0.01964943729729648)),
 (66, np.float64(0.02279803762937766)),
 (67, np.float64(0.16216216216216217)),
 (68, np.float64(0.12427395320024)),
 (69, np.float64(0.026757199700553222)),
 (70, np.float64(0.08108108108108109)),
 (71, np.float64(0.07435223956449145)),
 (72, np.float64(0.1389425035941821)),
 (73, np.float64(0.03427955850955305)),
 (74, np.float64(0.20323743847971518)),
 (75, np.float64(0.10810810810810811)),
 (76, np.float64(0.07271792483455794)),
 (77, np.float64(0.014530954842977409)),
 (78, np.float64(0.050734628943184104)),
 (79, np.float64(0.06314740019611717)),
 (80, np.float64(0.05114214254947678)),
 (81, np.float64(0.11168711865749101)),
 (82, np.float64(0.07521183158458504)),
 (83, np.float64(0.1841637022064523)),
 (84, np.float64(0.12527215359889848)),
 (85, np.float64(0.11507929111375009)),
 (86, np.float64(0.07118684968143743)),
 (87, np.float64(0.11277677488692017)),
 (88, np.float64(0.09004503377814962)),
 (89, np.float64(0.058352204610730346)),
 (90, np.float64(0.06213697660012)),
 (91, np.float64(0.16916516233038026)),
 (92, np.float64(0.06314740019611717)),
 (93, np.float64(0.07271792483455794)),
 (94, np.float64(0.18316875326179907)),
 (95, np.float64(0.14091341769030624)),
 (96, np.float64(0.07702442489446452)),
 (97, np.float64(0.07045670884515312)),
 (98, np.float64(0.07897471897389846)),
 (99, np.float64(0.02702702702702703)),
 (100, np.float64(0.07009996372327816)),
 (101, np.float64(0.07702442489446452)),
 (102, np.float64(0.1252721535988985)),
 (103, np.float64(0.07974522228289)),
 (104, np.float64(0.055577001437672836)),
 (105, np.float64(0.10283867552865913)),
 (106, np.float64(0.06263607679944924)),
 (107, np.float64(0.06263607679944924)),
 (108, np.float64(0.14704292441876157)),
 (109, np.float64(0.06711560552140244)),
 (110, np.float64(0.04516387521771449)),
 (111, np.float64(0.15042366316917008)),
 (112, np.float64(0.07702442489446452)),
 (113, np.float64(0.04355035563093422)),
 (114, np.float64(0.04649905549752771)),
 (115, np.float64(0.04474373701426829)),
 (116, np.float64(0.048478616556371965)),
 (117, np.float64(0.059053859535749265)),
 (118, np.float64(0.033912921674035035)),
 (119, np.float64(0.04355035563093422)),
 (120, np.float64(0.0)),
 (121, np.float64(0.11277677488692017)),
 (122, np.float64(0.11624763874381927)),
 (123, np.float64(0.1139901881468883)),
 (124, np.float64(0.06839411288813299)),
 (125, np.float64(0.0792290665533957)),
 (126, np.float64(0.13334518676566626)),
 (127, np.float64(0.14704292441876154)),
 (128, np.float64(0.0)),
 (129, np.float64(0.09394227846020416)),
 (130, np.float64(0.027399831217559546)),
 (131, np.float64(0.10529962529853128)),
 (132, np.float64(0.04559607525875532)),
 (133, np.float64(0.029061909685954818)),
 (134, np.float64(0.1289651760438322)),
 (135, np.float64(0.0)),
 (136, np.float64(0.024507154069793594)),
 (137, np.float64(0.03039738350583688)),
 (138, np.float64(0.12996881122750908)),
 (139, np.float64(0.12050719759100866)),
 (140, np.float64(0.04516387521771449)),
 (141, np.float64(0.0885807893036239)),
 (142, np.float64(0.08458258116519013)),
 (143, np.float64(0.08710071126186844)),
 (144, np.float64(0.05134961659630968)),
 (145, np.float64(0.019374606457303215)),
 (146, np.float64(0.01635831064016904)),
 (147, np.float64(0.056388387443460086)),
 (148, np.float64(0.09863939238321438)),
 (149, np.float64(0.15608456220771372)),
 (150, np.float64(0.1675306779862365)),
 (151, np.float64(0.20134681656420733)),
 (152, np.float64(0.08336550215650926)),
 (153, np.float64(0.07916524933276792)),
 (154, np.float64(0.06213697660012)),
 (155, np.float64(0.020878692266483083)),
 (156, np.float64(0.06117355427146393)),
 (157, np.float64(0.10067340828210367)),
 (158, np.float64(0.13423121104280486)),
 (159, np.float64(0.06327719971683327)),
 (160, np.float64(0.11806886145601307)),
 (161, np.float64(0.03287979746107146)),
 (162, np.float64(0.03224129401095805)),
 (163, np.float64(0.05264981264926564)),
 (164, np.float64(0.08108108108108109)),
 (165, np.float64(0.04604092555161308)),
 (166, np.float64(0.12535305264097507)),
 (167, np.float64(0.0885807893036239)),
 (168, np.float64(0.1754942736973651)),
 (169, np.float64(0.08948747402853657)),
 (170, np.float64(0.1061190899945022)),
 (171, np.float64(0.02302046277580654)),
 (172, np.float64(0.2102998911698345)),
 (173, np.float64(0.02348556961505104)),
 (174, np.float64(0.07702442489446452)),
 (175, np.float64(0.07194017065667525)),
 (176, np.float64(0.029526929767874632)),
 (177, np.float64(0.0)),
 (178, np.float64(0.024784079854830485)),
 (179, np.float64(0.07543142864047142)),
 (180, np.float64(0.022167554926073633)),
 (181, np.float64(0.04516387521771449)),
 (182, np.float64(0.1186447494690624)),
 (183, np.float64(0.07091039485189417)),
 (184, np.float64(0.17757120130114434)),
 (185, np.float64(0.05134961659630968)),
 (186, np.float64(0.05937393699957594)),
 (187, np.float64(0.1559625734730109)),
 (188, np.float64(0.022371868507134143)),
 (189, np.float64(0.11314714296070713)),
 (190, np.float64(0.08489527199560176)),
 (191, np.float64(0.04901430813958719)),
 (192, np.float64(0.047960113771116836)),
 (193, np.float64(0.07983920607777244)),
 (194, np.float64(0.0)),
 (195, np.float64(0.059053859535749265)),
 (196, np.float64(0.051987524491003634)),
 (197, np.float64(0.037229039552497)),
 (198, np.float64(0.058123819371909635)),
 (199, np.float64(0.08948747402853657)),
 (200, np.float64(0.10762440050012628)),
 (201, np.float64(0.0)),
 (202, np.float64(0.03106848830006)),
 (203, np.float64(0.08336550215650926)),
 (204, np.float64(0.04956815970966097)),
 (205, np.float64(0.07543142864047142)),
 (206, np.float64(0.11241002017619531)),
 (207, np.float64(0.07798128673650545)),
 (208, np.float64(0.12427395320024)),
 (209, np.float64(0.06711560552140244)),
 (210, np.float64(0.07521183158458504)),
 (211, np.float64(0.024784079854830485)),
 (212, np.float64(0.06774581282657174)),
 (213, np.float64(0.05937393699957594)),
 (214, np.float64(0.0)),
 (215, np.float64(0.06711560552140243)),
 (216, np.float64(0.06575959492214292)),
 (217, np.float64(0.08710071126186844)),
 (218, np.float64(0.03771571432023571)),
 (219, np.float64(0.09158437663089952)),
 (220, np.float64(0.1771615786072478)),
 (221, np.float64(0.047960113771116836)),
 (222, np.float64(0.08094446585163528)),
 (223, np.float64(0.10810810810810811)),
 (224, np.float64(0.061649620239508984)),
 (225, np.float64(0.04697113923010208)),
 (226, np.float64(0.030528125543633176)),
 (227, np.float64(0.08219949365267865)),
 (228, np.float64(0.11185934253567072)),
 (229, np.float64(0.11314714296070713)),
 (230, np.float64(0.0930725988812425)),
 (231, np.float64(0.0)),
 (232, np.float64(0.11277677488692017)),
 (233, np.float64(0.10514994558491725)),
 (234, np.float64(0.0863465783552691)),
 (235, np.float64(0.07702442489446452)),
 (236, np.float64(0.11624763874381927)),
 (237, np.float64(0.06575959492214292)),
 (238, np.float64(0.11097798692504908)),
 (239, np.float64(0.09555497043061453)),
 (240, np.float64(0.047457899787624956)),
 (241, np.float64(0.07702442489446452)),
 (242, np.float64(0.08108108108108109)),
 (243, np.float64(0.09299811099505542)),
 (244, np.float64(0.09320546490018)),
 (245, np.float64(0.08108108108108109)),
 (246, np.float64(0.07696578428840449)),
 (247, np.float64(0.0)),
 (248, np.float64(0.04474373701426829)),
 (249, np.float64(0.14019992744655632)),
 (250, np.float64(0.0)),
 (251, np.float64(0.04109974682633932)),
 (252, np.float64(0.020391184757154644)),
 (253, np.float64(0.06420877537090426)),
 (254, np.float64(0.06974858324629157)),
 (255, np.float64(0.0)),
 (256, np.float64(0.11314714296070713)),
 (257, np.float64(0.0533380747062665)),
 (258, np.float64(0.0178315737905373)),
 (259, np.float64(0.06213697660012)),
 (260, np.float64(0.20343336780168372)),
 (261, np.float64(0.024507154069793594)),
 (262, np.float64(0.11083777463036817)),
 (263, np.float64(0.10067340828210367)),
 (264, np.float64(0.0)),
 (265, np.float64(0.027399831217559546)),
 (266, np.float64(0.10028244211278005)),
 (267, np.float64(0.06711560552140244)),
 (268, np.float64(0.0533380747062665)),
 (269, np.float64(0.029526929767874632)),
 (270, np.float64(0.08867021970429453)),
 (271, np.float64(0.07045670884515312)),
 (272, np.float64(0.028194193721730043)),
 (273, np.float64(0.021049133398705722)),
 (274, np.float64(0.09097816785925636)),
 (275, np.float64(0.1453095484297741)),
 (276, np.float64(0.06213697660012)),
 (277, np.float64(0.053494721371611896)),
 (278, np.float64(0.11742784807525519)),
 (279, np.float64(0.07118684968143743)),
 (280, np.float64(0.0)),
 (281, np.float64(0.06532553344640132)),
 (282, np.float64(0.022581937608857246)),
 (283, np.float64(0.027788500718836418)),
 (284, np.float64(0.0186145197762485)),
 (285, np.float64(0.019374606457303215)),
 (286, np.float64(0.07916524933276792)),
 (287, np.float64(0.025993762245501817)),
 (288, np.float64(0.027788500718836418)),
 (289, np.float64(0.04649905549752771)),
 (290, np.float64(0.06213697660012)),
 (291, np.float64(0.050141221056390024)),
 (292, np.float64(0.08718572905786445)),
 (293, np.float64(0.029526929767874632)),
 (294, np.float64(0.14309095175803563)),
 (295, np.float64(0.106676149412533)),
 (296, np.float64(0.03929887459459296)),
 (297, np.float64(0.04474373701426829)),
 (298, np.float64(0.0)),
 (299, np.float64(0.059808916712167495)),
 (300, np.float64(0.17757120130114434)),
 (301, np.float64(0.09428928580058928)),
 (302, np.float64(0.07118684968143743)),
 (303, np.float64(0.028194193721730043)),
 (304, np.float64(0.06645435190240834)),
 (305, np.float64(0.19101436199010396)),
 (306, np.float64(0.08219949365267865)),
 (307, np.float64(0.10972379887386347)),
 (308, np.float64(0.06711560552140244)),
 (309, np.float64(0.06213697660012)),
 (310, np.float64(0.03106848830006)),
 (311, np.float64(0.15042366316917005)),
 (312, np.float64(0.10269923319261937)),
 (313, np.float64(0.055577001437672836)),
 (314, np.float64(0.0)),
 (315, np.float64(0.08458258116519013)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.09863939238321438)),
 (320, np.float64(0.030528125543633176)),
 (321, np.float64(0.0)),
 (322, np.float64(0.20795009796401454)),
 (323, np.float64(0.03001501125938321)),
 (324, np.float64(0.024784079854830485)),
 (325, np.float64(0.09863939238321438)),
 (326, np.float64(0.056388387443460086)),
 (327, np.float64(0.027399831217559546)),
 (328, np.float64(0.02702702702702703)),
 (329, np.float64(0.07897471897389846)),
 (330, np.float64(0.10146925788636821)),
 (331, np.float64(0.09208185110322616)),
 (332, np.float64(0.10810810810810811)),
 (333, np.float64(0.025070610528195012)),
 (334, np.float64(0.09802861627917438)),
 (335, np.float64(0.04604092555161308)),
 (336, np.float64(0.07009996372327816)),
 (337, np.float64(0.04559607525875532)),
 (338, np.float64(0.0)),
 (339, np.float64(0.048478616556371965)),
 (340, np.float64(0.04956815970966097)),
 (341, np.float64(0.08336550215650926)),
 (342, np.float64(0.16240619866164335)),
 (343, np.float64(0.01964943729729648)),
 (344, np.float64(0.03001501125938321)),
 (345, np.float64(0.023249527748763855)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.06105625108726635)),
 (349, np.float64(0.07610194341477616)),
 (350, np.float64(0.04901430813958719)),
 (351, np.float64(0.0)),
 (352, np.float64(0.027788500718836418)),
 (353, np.float64(0.041757384532966166)),
 (354, np.float64(0.02177517781546711)),
 (355, np.float64(0.036992662308349696)),
 (356, np.float64(0.09004503377814962)),
 (357, np.float64(0.0)),
 (358, np.float64(0.06213697660012)),
 (359, np.float64(0.03163859985841663)),
 (360, np.float64(0.021049133398705722)),
 (361, np.float64(0.07610194341477616)),
 (362, np.float64(0.09672388203287416)),
 (363, np.float64(0.10042266465917388)),
 (364, np.float64(0.023728949893812478)),
 (365, np.float64(0.07610194341477616)),
 (366, np.float64(0.05723638070321425)),
 (367, np.float64(0.0)),
 (368, np.float64(0.13151918984428584)),
 (369, np.float64(0.1283740414907742)),
 (370, np.float64(0.05134961659630968)),
 (371, np.float64(0.09695723311274393)),
 (372, np.float64(0.047960113771116836)),
 (373, np.float64(0.17139779254776524)),
 (374, np.float64(0.03874921291460643)),
 (375, np.float64(0.061649620239508984)),
 (376, np.float64(0.04697113923010208)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.05114214254947678)),
 (380, np.float64(0.05264981264926564)),
 (381, np.float64(0.08489527199560176)),
 (382, np.float64(0.0)),
 (383, np.float64(0.04393747751637468)),
 (384, np.float64(0.029061909685954818)),
 (385, np.float64(0.0)),
 (386, np.float64(0.02177517781546711)),
 (387, np.float64(0.023980056885558418)),
 (388, np.float64(0.0)),
 (389, np.float64(0.0885807893036239)),
 (390, np.float64(0.02632490632463282)),
 (391, np.float64(0.056949479745149925)),
 (392, np.float64(0.030528125543633176)),
 (393, np.float64(0.0)),
 (394, np.float64(0.024784079854830485)),
 (395, np.float64(0.051987524491003634)),
 (396, np.float64(0.04433510985214727)),
 (397, np.float64(0.051987524491003634)),
 (398, np.float64(0.0)),
 (399, np.float64(0.024239308278185982)),
 (400, np.float64(0.09004503377814962)),
 (401, np.float64(0.030528125543633176)),
 (402, np.float64(0.07798128673650545)),
 (403, np.float64(0.08419653359482289)),
 (404, np.float64(0.06213697660012)),
 (405, np.float64(0.056388387443460086)),
 (406, np.float64(0.020878692266483083)),
 (407, np.float64(0.021586644588817275)),
 (408, np.float64(0.03287979746107146)),
 (409, np.float64(0.0)),
 (410, np.float64(0.09913631941932194)),
 (411, np.float64(0.05134961659630968)),
 (412, np.float64(0.09491579957524991)),
 (413, np.float64(0.1453095484297741)),
 (414, np.float64(0.03001501125938321)),
 (415, np.float64(0.05446449315986979)),
 (416, np.float64(0.05134961659630968)),
 (417, np.float64(0.03224129401095805)),
 (418, np.float64(0.03504998186163908)),
 (419, np.float64(0.06974858324629157)),
 (420, np.float64(0.11290968804428622)),
 (421, np.float64(0.02348556961505104)),
 (422, np.float64(0.1144727614064285)),
 (423, np.float64(0.04244763599780088)),
 (424, np.float64(0.037470006725398436)),
 (425, np.float64(0.06475993376645182)),
 (426, np.float64(0.05413539955388112)),
 (427, np.float64(0.028194193721730043)),
 (428, np.float64(0.056205010088097654)),
 (429, np.float64(0.0)),
 (430, np.float64(0.05134961659630968)),
 (431, np.float64(0.024507154069793594)),
 (432, np.float64(0.11510231387903269)),
 (433, np.float64(0.03106848830006)),
 (434, np.float64(0.0)),
 (435, np.float64(0.03587480016670876)),
 (436, np.float64(0.0)),
 (437, np.float64(0.02632490632463282)),
 (438, np.float64(0.12253577034896797)),
 (439, np.float64(0.02632490632463282)),
 (440, np.float64(0.024784079854830485)),
 (441, np.float64(0.05723638070321425)),
 (442, np.float64(0.04604092555161308)),
 (443, np.float64(0.06367145399670132)),
 (444, np.float64(0.0)),
 (445, np.float64(0.10028244211278005)),
 (446, np.float64(0.023249527748763855)),
 (447, np.float64(0.06532553344640132)),
 (448, np.float64(0.02177517781546711)),
 (449, np.float64(0.11115400287534567)),
 (450, np.float64(0.02122381799890044)),
 (451, np.float64(0.025367314471592052)),
 (452, np.float64(0.03106848830006)),
 (453, np.float64(0.024784079854830485)),
 (454, np.float64(0.11742784807525519)),
 (455, np.float64(0.061649620239508984)),
 (456, np.float64(0.04355035563093422)),
 (457, np.float64(0.08718572905786445)),
 (458, np.float64(0.04393747751637468)),
 (459, np.float64(0.03427955850955305)),
 (460, np.float64(0.024239308278185982)),
 (461, np.float64(0.1453095484297741)),
 (462, np.float64(0.03271662128033808)),
 (463, np.float64(0.03287979746107146)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.14349920066683505)),
 (467, np.float64(0.10701462561817378)),
 (468, np.float64(0.028194193721730043)),
 (469, np.float64(0.06025359879550432)),
 (470, np.float64(0.04559607525875532)),
 (471, np.float64(0.06475993376645182)),
 (472, np.float64(0.10959932487023819)),
 (473, np.float64(0.09299811099505542)),
 (474, np.float64(0.0)),
 (475, np.float64(0.04433510985214727)),
 (476, np.float64(0.13151918984428584)),
 (477, np.float64(0.0)),
 (478, np.float64(0.05479966243511909)),
 (479, np.float64(0.08968700041677191)),
 (480, np.float64(0.09802861627917438)),
 (481, np.float64(0.0)),
 (482, np.float64(0.02196873875818734)),
 (483, np.float64(0.12427395320024)),
 (484, np.float64(0.029526929767874632)),
 (485, np.float64(0.05264981264926564)),
 (486, np.float64(0.08138962667412651)),
 (487, np.float64(0.1289651760438322)),
 (488, np.float64(0.06746792083200746)),
 (489, np.float64(0.0)),
 (490, np.float64(0.14349920066683505)),
 (491, np.float64(0.10439346133241542)),
 (492, np.float64(0.07702442489446452)),
 (493, np.float64(0.03093071161985594)),
 (494, np.float64(0.0)),
 (495, np.float64(0.1898315991504998)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.0685591170191061)),
 (499, np.float64(0.0)),
 (500, np.float64(0.02567480829815484)),
 (501, np.float64(0.08284930213349333)),
 (502, np.float64(0.13300532955644181)),
 (503, np.float64(0.07521183158458504)),
 (504, np.float64(0.0)),
 (505, np.float64(0.1371182340382122)),
 (506, np.float64(0.03587480016670876)),
 (507, np.float64(0.25903973506580724)),
 (508, np.float64(0.10269923319261937)),
 (509, np.float64(0.022167554926073633)),

In [55]:
# sorting the list
sorted(enumerate(similarity[0]), reverse=True, key=lambda x : x[1])

[(0, np.float64(0.9999999999999998)),
 (1214, np.float64(0.29061909685954823)),
 (507, np.float64(0.25903973506580724)),
 (3728, np.float64(0.25732511773283273)),
 (539, np.float64(0.2500965064695278)),
 (582, np.float64(0.2484013136974297)),
 (2405, np.float64(0.24507154069793594)),
 (1202, np.float64(0.24239308278185984)),
 (61, np.float64(0.23490461932490855)),
 (1192, np.float64(0.23490461932490855)),
 (778, np.float64(0.23249527748763854)),
 (1916, np.float64(0.22830583024432843)),
 (4046, np.float64(0.22482004035239062)),
 (2782, np.float64(0.22147019900891643)),
 (172, np.float64(0.2102998911698345)),
 (2969, np.float64(0.20878692266483084)),
 (322, np.float64(0.20795009796401454)),
 (2329, np.float64(0.2071841649822589)),
 (3606, np.float64(0.20712325533373332)),
 (972, np.float64(0.20668850837512243)),
 (1087, np.float64(0.20608503698969144)),
 (4190, np.float64(0.2056773510573183)),
 (1440, np.float64(0.20549873413169661)),
 (260, np.float64(0.20343336780168372)),
 (74, np.float64(0.20323743847971518)),
 (151, np.float64(0.20134681656420733)),
 (3671, np.float64(0.2005648842255601)),
 (577, np.float64(0.20032733246124987)),
 (973, np.float64(0.20032733246124987)),
 (47, np.float64(0.1979131233319198)),
 (942, np.float64(0.19184045508446734)),
 (305, np.float64(0.19101436199010396)),
 (4405, np.float64(0.18983159915049982)),
 (4, np.float64(0.1898315991504998)),
 (495, np.float64(0.1898315991504998)),
 (1199, np.float64(0.1898315991504998)),
 (27, np.float64(0.18944220058835154)),
 (3325, np.float64(0.18857857160117855)),
 (1327, np.float64(0.18641092980036)),
 (1069, np.float64(0.18427434427242975)),
 (83, np.float64(0.1841637022064523)),
 (2997, np.float64(0.18380365552345193)),
 (94, np.float64(0.18316875326179907)),
 (3997, np.float64(0.18316875326179907)),
 (1319, np.float64(0.17937400083354382)),
 (184, np.float64(0.17757120130114434)),
 (300, np.float64(0.17757120130114434)),
 (2200, np.float64(0.17757120130114434)),
 (220, np.float64(0.1771615786072478)),
 (1273, np.float64(0.1771615786072478)),
 (168, np.float64(0.1754942736973651)),
 (4336, np.float64(0.1754942736973651)),
 (3160, np.float64(0.1742014225237369)),
 (3536, np.float64(0.17348855898381338)),
 (931, np.float64(0.17170914210964275)),
 (36, np.float64(0.17155007848855516)),
 (373, np.float64(0.17139779254776524)),
 (1827, np.float64(0.1696751579473019)),
 (91, np.float64(0.16916516233038026)),
 (1978, np.float64(0.16916516233038026)),
 (529, np.float64(0.1678603981989089)),
 (150, np.float64(0.1675306779862365)),
 (661, np.float64(0.16702953813186466)),
 (41, np.float64(0.16610264925668733)),
 (595, np.float64(0.1643989873053573)),
 (1533, np.float64(0.1643989873053573)),
 (342, np.float64(0.16240619866164335)),
 (67, np.float64(0.16216216216216217)),
 (1176, np.float64(0.16216216216216217)),
 (31, np.float64(0.16120647005479025)),
 (2511, np.float64(0.16120647005479025)),
 (4008, np.float64(0.15949044456578)),
 (2727, np.float64(0.15819299929208316)),
 (149, np.float64(0.15608456220771372)),
 (26, np.float64(0.1559625734730109)),
 (187, np.float64(0.1559625734730109)),
 (1342, np.float64(0.15404884978892902)),
 (838, np.float64(0.15393156857680898)),
 (111, np.float64(0.15042366316917008)),
 (513, np.float64(0.15042366316917008)),
 (1379, np.float64(0.15042366316917008)),
 (311, np.float64(0.15042366316917005)),
 (581, np.float64(0.15007505629691606)),
 (2071, np.float64(0.15007505629691606)),
 (2756, np.float64(0.14982047586544328)),
 (1271, np.float64(0.1487044791289829)),
 (1295, np.float64(0.1487044791289829)),
 (3352, np.float64(0.14763464883937316)),
 (7, np.float64(0.14704292441876157)),
 (52, np.float64(0.14704292441876157)),
 (108, np.float64(0.14704292441876157)),
 (127, np.float64(0.14704292441876154)),
 (1392, np.float64(0.14615084586538157)),
 (1475, np.float64(0.14615084586538157)),
 (1934, np.float64(0.1454358496691159)),
 (275, np.float64(0.1453095484297741)),
 (413, np.float64(0.1453095484297741)),
 (461, np.float64(0.1453095484297741)),
 (579, np.float64(0.1453095484297741)),
 (1353, np.float64(0.1438803413133505)),
 (466, np.float64(0.14349920066683505)),
 (490, np.float64(0.14349920066683505)),
 (1484, np.float64(0.14349920066683505)),
 (294, np.float64(0.14309095175803563)),
 (937, np.float64(0.14309095175803563)),
 (3407, np.float64(0.14309095175803563)),
 (568, np.float64(0.1430909517580356)),
 (1054, np.float64(0.14237369936287486)),
 (17, np.float64(0.14165281524036175)),
 (1961, np.float64(0.14165281524036175)),
 (2492, np.float64(0.14097096860865022)),
 (95, np.float64(0.14091341769030624)),
 (56, np.float64(0.14019992744655632)),
 (249, np.float64(0.14019992744655632)),
 (1325, np.float64(0.14019992744655632)),
 (3779, np.float64(0.14019992744655632)),
 (46, np.float64(0.1389425035941821)),
 (72, np.float64(0.1389425035941821)),
 (843, np.float64(0.1389425035941821)),
 (859, np.float64(0.1389425035941821)),
 (2165, np.float64(0.1389425035941821)),
 (4538, np.float64(0.13812277665483924)),
 (505, np.float64(0.1371182340382122)),
 (3980, np.float64(0.1371182340382122)),
 (1804, np.float64(0.13699915608779772)),
 (4348, np.float64(0.13678822577626598)),
 (1320, np.float64(0.13657399193174952)),
 (777, np.float64(0.1354916256531435)),
 (1556, np.float64(0.13513513513513514)),
 (668, np.float64(0.1342312110428049)),
 (935, np.float64(0.1342312110428049)),
 (1369, np.float64(0.1342312110428049)),
 (2580, np.float64(0.1342312110428049)),
 (158, np.float64(0.13423121104280486)),
 (126, np.float64(0.13334518676566626)),
 (1013, np.float64(0.13334518676566626)),
 (4077, np.float64(0.13334518676566626)),
 (502, np.float64(0.13300532955644181)),
 (2129, np.float64(0.13300532955644181)),
 (3620, np.float64(0.1316245316231641)),
 (368, np.float64(0.13151918984428584)),
 (476, np.float64(0.13151918984428584)),
 (2374, np.float64(0.13151918984428584)),
 (2968, np.float64(0.13151918984428584)),
 (2869, np.float64(0.13065106689280268)),
 (14, np.float64(0.12996881122750908)),
 (138, np.float64(0.12996881122750908)),
 (1084, np.float64(0.12996881122750908)),
 (2446, np.float64(0.12996881122750908)),
 (2682, np.float64(0.12996881122750908)),
 (4228, np.float64(0.12996881122750908)),
 (134, np.float64(0.1289651760438322)),
 (487, np.float64(0.1289651760438322)),
 (773, np.float64(0.1289651760438322)),
 (1770, np.float64(0.1289651760438322)),
 (369, np.float64(0.1283740414907742)),
 (2177, np.float64(0.1283740414907742)),
 (3626, np.float64(0.1283740414907742)),
 (1737, np.float64(0.12629480039223434)),
 (166, np.float64(0.12535305264097507)),
 (754, np.float64(0.12535305264097507)),
 (1297, np.float64(0.12535305264097507)),
 (102, np.float64(0.1252721535988985)),
 (84, np.float64(0.12527215359889848)),
 (68, np.float64(0.12427395320024)),
 (208, np.float64(0.12427395320024)),
 (483, np.float64(0.12427395320024)),
 (1094, np.float64(0.12427395320024)),
 (1156, np.float64(0.12427395320024)),
 (1874, np.float64(0.12427395320024)),
 (2648, np.float64(0.12427395320024)),
 (557, np.float64(0.12392039927415242)),
 (2327, np.float64(0.12329924047901797)),
 (2476, np.float64(0.12329924047901797)),
 (2670, np.float64(0.12329924047901797)),
 (3081, np.float64(0.12329924047901797)),
 (438, np.float64(0.12253577034896797)),
 (1654, np.float64(0.1221125021745327)),
 (3374, np.float64(0.1221125021745327)),
 (4673, np.float64(0.1221125021745327)),
 (549, np.float64(0.12119654139092992)),
 (870, np.float64(0.12119654139092992)),
 (3233, np.float64(0.1211965413909299)),
 (139, np.float64(0.12050719759100866)),
 (1000, np.float64(0.12050719759100866)),
 (1002, np.float64(0.12006004503753284)),
 (1045, np.float64(0.12006004503753284)),
 (1272, np.float64(0.12006004503753284)),
 (1829, np.float64(0.12006004503753284)),
 (2056, np.float64(0.12006004503753284)),
 (900, np.float64(0.11990028442779209)),
 (1669, np.float64(0.11961783342433499)),
 (1711, np.float64(0.11961783342433499)),
 (2785, np.float64(0.11961783342433499)),
 (3998, np.float64(0.11961783342433499)),
 (182, np.float64(0.1186447494690624)),
 (2280, np.float64(0.1186447494690624)),
 (678, np.float64(0.11810771907149853)),
 (2737, np.float64(0.11810771907149853)),
 (781, np.float64(0.11810771907149852)),
 (160, np.float64(0.11806886145601307)),
 (589, np.float64(0.1178966237837789)),
 (278, np.float64(0.11742784807525519)),
 (454, np.float64(0.11742784807525519)),
 (1613, np.float64(0.11742784807525519)),
 (2543, np.float64(0.11742784807525519)),
 (1493, np.float64(0.11706342165578529)),
 (3210, np.float64(0.1166080974034697)),
 (122, np.float64(0.11624763874381927)),
 (236, np.float64(0.11624763874381927)),
 (1218, np.float64(0.11624763874381927)),
 (1299, np.float64(0.11624763874381927)),
 (1414, np.float64(0.11624763874381927)),
 (432, np.float64(0.11510231387903269)),
 (85, np.float64(0.11507929111375009)),
 (3145, np.float64(0.11466596451673744)),
 (50, np.float64(0.1144727614064285)),
 (422, np.float64(0.1144727614064285)),
 (536, np.float64(0.11399018814688831)),
 (1508, np.float64(0.11399018814688831)),
 (123, np.float64(0.1139901881468883)),
 (889, np.float64(0.11394547734377711)),
 (189, np.float64(0.11314714296070713)),
 (229, np.float64(0.11314714296070713)),
 (256, np.float64(0.11314714296070713)),
 (627, np.float64(0.11314714296070713)),
 (808, np.float64(0.11314714296070713)),
 (1346, np.float64(0.11314714296070713)),
 (3719, np.float64(0.11314714296070713)),
 (420, np.float64(0.11290968804428622)),
 (2368, np.float64(0.11290968804428622)),
 (87, np.float64(0.11277677488692017)),
 (121, np.float64(0.11277677488692017)),
 (232, np.float64(0.11277677488692017)),
 (4468, np.float64(0.11277677488692017)),
 (206, np.float64(0.11241002017619531)),
 (228, np.float64(0.11185934253567072)),
 (81, np.float64(0.11168711865749101)),
 (28, np.float64(0.11115400287534567)),
 (449, np.float64(0.11115400287534567)),
 (1029, np.float64(0.11115400287534567)),
 (1612, np.float64(0.11115400287534567)),
 (1941, np.float64(0.11115400287534567)),
 (3006, np.float64(0.11115400287534567)),
 (1570, np.float64(0.1109779869250491)),
 (238, np.float64(0.11097798692504908)),
 (262, np.float64(0.11083777463036817)),
 (3307, np.float64(0.11083777463036817)),
 (653, np.float64(0.11028219331407116)),
 (1520, np.float64(0.11028219331407116)),
 (5, np.float64(0.1098436937909367)),
 (692, np.float64(0.1098436937909367)),
 (3091, np.float64(0.1098436937909367)),
 (3628, np.float64(0.1098436937909367)),
 (307, np.float64(0.10972379887386347)),
 (472, np.float64(0.10959932487023819)),
 (786, np.float64(0.10959932487023819)),
 (1235, np.float64(0.10959932487023819)),
 (3138, np.float64(0.10959932487023819)),
 (3426, np.float64(0.10959932487023819)),
 (3496, np.float64(0.10959932487023819)),
 (4777, np.float64(0.10959932487023819)),
 (740, np.float64(0.10887588907733556)),
 (572, np.float64(0.10887588907733554)),
 (939, np.float64(0.10827079910776224)),
 (21, np.float64(0.10810810810810811)),
 (75, np.float64(0.10810810810810811)),
 (223, np.float64(0.10810810810810811)),
 (332, np.float64(0.10810810810810811)),
 (687, np.float64(0.10810810810810811)),
 (814, np.float64(0.10810810810810811)),
 (1492, np.float64(0.10793322294408637)),
 (200, np.float64(0.10762440050012628)),
 (1571, np.float64(0.10762440050012628)),
 (2157, np.float64(0.10762440050012628)),
 (2630, np.float64(0.10762440050012628)),
 (467, np.float64(0.10701462561817378)),
 (295, np.float64(0.106676149412533)),
 (2068, np.float64(0.106676149412533)),
 (2813, np.float64(0.106676149412533)),
 (3338, np.float64(0.106676149412533)),
 (170, np.float64(0.1061190899945022)),
 (2494, np.float64(0.1061190899945022)),
 (131, np.float64(0.10529962529853128)),
 (1035, np.float64(0.10529962529853128)),
 (3150, np.float64(0.10529962529853128)),
 (541, np.float64(0.10524566699352861)),
 (2435, np.float64(0.10524566699352861)),
 (233, np.float64(0.10514994558491725)),
 (1164, np.float64(0.10514994558491725)),
 (1497, np.float64(0.10514994558491725)),
 (1741, np.float64(0.10514994558491725)),
 (2319, np.float64(0.10514994558491725)),
 (2517, np.float64(0.10514994558491725)),
 (3619, np.float64(0.10514994558491725)),
 (3837, np.float64(0.10514994558491725)),
 (4133, np.float64(0.10514994558491725)),
 (491, np.float64(0.10439346133241542)),
 (654, np.float64(0.10439346133241542)),
 (1451, np.float64(0.10439346133241542)),
 (1080, np.float64(0.10397504898200727)),
 (1610, np.float64(0.10397504898200727)),
 (2144, np.float64(0.10397504898200727)),
 (3632, np.float64(0.10397504898200727)),
 (3753, np.float64(0.10397504898200727)),
 (3872, np.float64(0.10397504898200727)),
 (4095, np.float64(0.10397504898200727)),
 (2102, np.float64(0.10356162766686666)),
 (3053, np.float64(0.10283867552865915)),
 (105, np.float64(0.10283867552865913)),
 (624, np.float64(0.10283867552865913)),
 (1278, np.float64(0.10283867552865913)),
 (2452, np.float64(0.10283867552865913)),
 (2758, np.float64(0.10283867552865913)),
 (3659, np.float64(0.10283867552865913)),
 (4196, np.float64(0.10283867552865913)),
 (3439, np.float64(0.10274936706584831)),
 (10, np.float64(0.10269923319261937)),
 (312, np.float64(0.10269923319261937)),
 (508, np.float64(0.10269923319261937)),
 (1292, np.float64(0.10269923319261937)),
 (1767, np.float64(0.10269923319261937)),
 (2243, np.float64(0.10269923319261937)),
 (2095, np.float64(0.1019559237857732)),
 (330, np.float64(0.10146925788636821)),
 (643, np.float64(0.10146925788636821)),
 (1401, np.float64(0.1011805823145441)),
 (1435, np.float64(0.1011805823145441)),
 (157, np.float64(0.10067340828210367)),
 (263, np.float64(0.10067340828210367)),
 (1075, np.float64(0.10067340828210367)),
 (1880, np.float64(0.10067340828210367)),
 (2783, np.float64(0.10067340828210367)),
 (3952, np.float64(0.10067340828210367)),
 (4016, np.float64(0.10067340828210367)),
 (4490, np.float64(0.10067340828210367)),
 (363, np.float64(0.10042266465917388)),
 (266, np.float64(0.10028244211278005)),
 (445, np.float64(0.10028244211278005)),
 (510, np.float64(0.10028244211278005)),
 (986, np.float64(0.10028244211278005)),
 (3618, np.float64(0.10028244211278005)),
 (3781, np.float64(0.10028244211278005)),
 (3933, np.float64(0.10028244211278005)),
 (1771, np.float64(0.09968152785361249)),
 (410, np.float64(0.09913631941932194)),
 (535, np.float64(0.09913631941932194)),
 (1107, np.float64(0.09913631941932194)),
 (1397, np.float64(0.09913631941932194)),
 (1819, np.float64(0.09913631941932194)),
 (2249, np.float64(0.09913631941932194)),
 (35, np.float64(0.09863939238321438)),
 (148, np.float64(0.09863939238321438)),
 (319, np.float64(0.09863939238321438)),
 (325, np.float64(0.09863939238321438)),
 (715, np.float64(0.09863939238321438)),
 (878, np.float64(0.09863939238321438)),
 (1154, np.float64(0.09863939238321438)),
 (1304, np.float64(0.09863939238321438)),
 (1723, np.float64(0.09863939238321438)),
 (1938, np.float64(0.09863939238321438)),
 (2049, np.float64(0.09863939238321438)),
 (4201, np.float64(0.09863939238321438)),
 (4472, np.float64(0.09863939238321438)),
 (9, np.float64(0.09802861627917438)),
 (334, np.float64(0.09802861627917438)),
 (480, np.float64(0.09802861627917438)),
 (898, np.float64(0.09802861627917438)),
 (1193, np.float64(0.09802861627917438)),
 (2237, np.float64(0.09802861627917438)),
 (2552, np.float64(0.09802861627917438)),
 (371, np.float64(0.09695723311274393)),
 (18, np.float64(0.09687303228651607)),
 (4545, np.float64(0.09687303228651607)),
 (33, np.float64(0.09672388203287416)),
 (362, np.float64(0.09672388203287416)),
 (791, np.float64(0.09672388203287416)),
 (1717, np.float64(0.09672388203287416)),
 (2558, np.float64(0.09672388203287416)),
 (2641, np.float64(0.09672388203287416)),
 (4254, np.float64(0.09672388203287416)),
 (4403, np.float64(0.09672388203287416)),
 (2588, np.float64(0.09592022754223367)),
 (239, np.float64(0.09555497043061453)),
 (11, np.float64(0.09491579957524991)),
 (412, np.float64(0.09491579957524991)),
 (1355, np.float64(0.09491579957524991)),
 (1688, np.float64(0.09491579957524991)),
 (2484, np.float64(0.09491579957524991)),
 (2646, np.float64(0.09491579957524991)),
 (2816, np.float64(0.09491579957524991)),
 (3405, np.float64(0.09491579957524991)),
 (3718, np.float64(0.09491579957524991)),
 (4343, np.float64(0.09491579957524991)),
 (660, np.float64(0.0949157995752499)),
 (920, np.float64(0.0949157995752499)),
 (1470, np.float64(0.0949157995752499)),
 (1569, np.float64(0.0949157995752499)),
 (1682, np.float64(0.0949157995752499)),
 (3535, np.float64(0.0949157995752499)),
 (4331, np.float64(0.0949157995752499)),
 (301, np.float64(0.09428928580058928)),
 (129, np.float64(0.09394227846020416)),
 (596, np.float64(0.09394227846020416)),
 (1442, np.float64(0.09394227846020416)),
 (1697, np.float64(0.09394227846020416)),
 (785, np.float64(0.09367501681349609)),
 (244, np.float64(0.09320546490018)),
 (978, np.float64(0.09320546490018)),
 (1752, np.float64(0.09320546490018)),
 (2089, np.float64(0.09320546490018)),
 (2392, np.float64(0.09320546490018)),
 (2647, np.float64(0.09320546490018)),
 (3734, np.float64(0.09320546490018)),
 (230, np.float64(0.0930725988812425)),
 (799, np.float64(0.0930725988812425)),
 (2566, np.float64(0.0930725988812425)),
 (243, np.float64(0.09299811099505542)),
 (473, np.float64(0.09299811099505542)),
 (813, np.float64(0.09299811099505542)),
 (995, np.float64(0.09299811099505542)),
 (43, np.float64(0.09208185110322616)),
 (331, np.float64(0.09208185110322616)),
 (602, np.float64(0.09208185110322616)),
 (1231, np.float64(0.09208185110322616)),
 (1842, np.float64(0.09208185110322616)),
 (3387, np.float64(0.09208185110322616)),
 (3879, np.float64(0.09208185110322616)),
 (12, np.float64(0.09158437663089952)),
 (219, np.float64(0.09158437663089952)),
 (511, np.float64(0.09158437663089952)),
 (2247, np.float64(0.09158437663089952)),
 (2955, np.float64(0.09158437663089952)),
 (1274, np.float64(0.09119215051751065)),
 (2792, np.float64(0.09119215051751065)),
 (2852, np.float64(0.09119215051751065)),
 (3460, np.float64(0.09119215051751065)),
 (4353, np.float64(0.09119215051751065)),
 (274, np.float64(0.09097816785925636)),
 (1902, np.float64(0.09032775043542898)),
 (2359, np.float64(0.09032775043542898)),
 (2709, np.float64(0.09032775043542898)),
 (2111, np.float64(0.0902256659231352)),
 (88, np.float64(0.09004503377814962)),
 (356, np.float64(0.09004503377814962)),
 (400, np.float64(0.09004503377814962)),
 (1025, np.float64(0.09004503377814962)),
 (1476, np.float64(0.09004503377814962)),
 (2656, np.float64(0.09004503377814962)),
 (2864, np.float64(0.09004503377814962)),
 (3320, np.float64(0.09004503377814962)),
 (3446, np.float64(0.09004503377814962)),
 (479, np.float64(0.08968700041677191)),
 (63, np.float64(0.08948747402853657)),
 (169, np.float64(0.08948747402853657)),
 (199, np.float64(0.08948747402853657)),
 (1779, np.float64(0.08948747402853657)),
 (2105, np.float64(0.08948747402853657)),
 (3551, np.float64(0.08948747402853657)),
 (270, np.float64(0.08867021970429453)),
 (827, np.float64(0.08867021970429453)),
 (2736, np.float64(0.08867021970429453)),
 (3554, np.float64(0.08867021970429453)),
 (2444, np.float64(0.0886379935648677)),
 (141, np.float64(0.0885807893036239)),
 (167, np.float64(0.0885807893036239)),
 (389, np.float64(0.0885807893036239)),
 (564, np.float64(0.0885807893036239)),
 (794, np.float64(0.0885807893036239)),
 (1247, np.float64(0.0885807893036239)),
 (1257, np.float64(0.0885807893036239)),
 (618, np.float64(0.08787495503274936)),
 (752, np.float64(0.08787495503274936)),
 (1017, np.float64(0.08787495503274936)),
 (1828, np.float64(0.08787495503274936)),
 (2876, np.float64(0.08787495503274936)),
 (4502, np.float64(0.08787495503274936)),
 (4516, np.float64(0.08787495503274936)),
 (4587, np.float64(0.08787495503274936)),
 (23, np.float64(0.08718572905786445)),
 (292, np.float64(0.08718572905786445)),
 (457, np.float64(0.08718572905786445)),
 (775, np.float64(0.08718572905786445)),
 (3133, np.float64(0.08718572905786445)),
 (3447, np.float64(0.08718572905786445)),
 (4754, np.float64(0.08718572905786445)),

In [56]:
# getting top 5 similer movies
sorted(enumerate(similarity[0]), reverse=True, key=lambda x : x[1])[1:6]

[(1214, np.float64(0.29061909685954823)),
 (507, np.float64(0.25903973506580724)),
 (3728, np.float64(0.25732511773283273)),
 (539, np.float64(0.2500965064695278)),
 (582, np.float64(0.2484013136974297))]

## Function by combining all of the above mentioned steps

In [57]:
def recommend_movies(movie):
    movie_index = df[df['title'] == movie].index[0]

    distance_with_all = similarity[movie_index]
    movies_list = sorted(list(enumerate(distance_with_all)), reverse=True, key=lambda x : x[1])[1:6]

    
    for i in movies_list:
        print(df.iloc[i[0]].title)

In [58]:
recommend_movies('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [59]:
import pickle

In [ ]:
pickle.dump(df, open("movies.pkl","wb"))

In [ ]:
pickle.dump(df.to_dict(), open("movies_dict.pkl","wb"))

In [ ]:
pickle.dump(similarity, open("similarity_matrics.pkl", "wb"))